---
repos:
  - repo: https://github.com/pre-commit/sync-pre-commit-deps
    rev: "v0.0.3"
    hooks:
      - id: sync-pre-commit-deps

  - repo: https://github.com/mbroton/import-future-annotations
    rev: "v1.0.0"
    hooks:
      - id: import-future-annotations

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.37.1"
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-json
      - id: check-illegal-windows-names
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: fix-byte-order-marker
      - id: check-case-conflict

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/psf/black
    rev: "25.9.0"
    hooks:
      # - id: black
      - id: black-jupyter
        types: [jupyter]

  - repo: https://github.com/hadialqattan/pycln
    rev: "v2.5.0"
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: "6.1.0"
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        types_or: [yaml, json, toml]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.45.0"
    hooks:
      - id: markdownlint-fix
        args:
          - "--fix"
          - "--config=.markdownlint.yaml"
        files: \.md$

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs
        language: python
        args: ["--pyi", "--line-length", "100", "--target-version", "py313"]
        additional_dependencies:
          - black==25.9.0

  - repo: https://github.com/pycqa/flake8
    rev: "7.3.0"
    hooks:
      - id: flake8
        # E501 - line length (black will handle most of the issues, and what it can't - should be ignored)
        # W503 - line break before binary operator (preference)
        # E704 - multiple statements on one line (does not account for overload decorator usage)
        # E203 - whitespace before ':' (black will handle this)
        args: ["--ignore=E501,W503,E704,E203", --config=setup.cfg]

  - repo: https://github.com/asottile/yesqa
    rev: "v1.5.0"
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8==7.3.0
          - black==25.9.0
          - ruff==0.14.3

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: "v0.24.1"
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  - repo: https://github.com/python-poetry/poetry
    rev: "2.2.1"
    hooks:
      - id: poetry-check

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.5"
    hooks:
      - id: forbid-crlf
      - id: remove-crlf

  - repo: https://github.com/shellcheck-py/shellcheck-py.git
    rev: "v0.11.0.1"
    hooks:
      - id: shellcheck

  - repo: https://github.com/crate-ci/typos
    rev: "v1.39.0"
    hooks:
      - id: typos
        args: [] # Ensure typos are only reported, not auto-fixed. Auto-fix is default behavior.

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.1"
    hooks:
      - id: codespell
        types_or: [python, markdown]
        additional_dependencies:
          - tomli
